AWSTemplateFormatVersion: '2010-09-09'
Description: To mount ec2 instances with EFS 
Resources:
  TcnFileSystem:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: String
      IpAddress: String
      SecurityGroups: 
        - String
      SubnetId: String
